[project]
name = "datasette-public"
version = "0.4a2"
description = "Make selected Datasette databases and tables visible to the public"
readme = "README.md"
authors = [{name = "Simon Willison"}]
license = "Apache-2.0"
classifiers=[
    "Framework :: Datasette",
]
requires-python = ">=3.10"
dependencies = [
    "datasette>=1.0a37",
]

[project.urls]
Homepage = "https://github.com/datasette/datasette-public"
Changelog = "https://github.com/datasette/datasette-public/releases"
Issues = "https://github.com/datasette/datasette-public/issues"
CI = "https://github.com/datasette/datasette-public/actions"

[project.entry-points.datasette]
public = "datasette_public"

[dependency-groups]
dev = ["pytest", "pytest-asyncio"]

[tool.uv]
package = true

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools.package-data]
datasette_public = ["templates/*"]
